//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cesitler
    {
        public byte cesit_id { get; set; }
        public string cesit_ad { get; set; }
        public string cesit_fiyat { get; set; }
        public Nullable<byte> yemek_fk_id { get; set; }
    
        public virtual Yemekler Yemekler { get; set; }
    }
}
