//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public byte fatura_id { get; set; }
        public string musteri_ad { get; set; }
        public string musteri_soyad { get; set; }
        public string odenecek_tutar { get; set; }
        public Nullable<byte> masa_fk_id { get; set; }
    
        public virtual Masalar Masalar { get; set; }
    }
}
