//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class Icecekcesit
    {
        public byte I_cesit_id { get; set; }
        public string I_cesit_ad { get; set; }
        public string I_cesit_fiyat { get; set; }
        public Nullable<byte> icecek_fk_id { get; set; }
    
        public virtual İcecekler İcecekler { get; set; }
    }
}
