//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class İcecekler
    {
        public byte icecek_id { get; set; }
        public string icecek_ad { get; set; }
    
        public virtual Icecekcesit Icecekcesit { get; set; }
    }
}
