//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Masalar()
        {
            this.Fatura = new HashSet<Fatura>();
        }
    
        public Nullable<byte> konum_id_fk { get; set; }
        public byte masa_id { get; set; }
        public string masa_no { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura> Fatura { get; set; }
        public virtual Kat_konum Kat_konum { get; set; }
    }
}
