//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabanı
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HesapSistemiEntities : DbContext
    {
        public HesapSistemiEntities()
            : base("name=HesapSistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cesitler> Cesitler { get; set; }
        public virtual DbSet<Fatura> Fatura { get; set; }
        public virtual DbSet<Icecekcesit> Icecekcesit { get; set; }
        public virtual DbSet<İcecekler> İcecekler { get; set; }
        public virtual DbSet<Kat_konum> Kat_konum { get; set; }
        public virtual DbSet<Masalar> Masalar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Yemekler> Yemekler { get; set; }
    }
}
